### PR TITLE
Update Utility.py

### PR DESCRIPTION
**Pull request by Zuckonit**
python 2.6 has no attribute PY2 in module six

### CODE REVIEW

**Comment by Zuckonit** [comment]
cannot be merged?

**Comment by kz26** [comment]
It sounds like your version of six is too old. The PY2 constant was added in six 1.4.0: https://bitbucket.org/gutworth/six/src/78315705481c3f5e491a3816e41aa66c54c8f965/CHANGES?at=default#cl-178

Please update your six library and see if that fixes the error.

**Comment by Zuckonit** [comment]
so, sys is more compatible

**Comment by kevmo314** [comment]
required six >= 1.4.0 in setup.py. has the same effect, is more readable. we're using the six library anyways and 1.4.0 was released > 1 year ago so it's not really new.

https://github.com/kz26/PyExcelerate/commit/ccfed2a6186a46773e66eeeb8348abb160c5aaf4

**Pull request closed without merging**
